'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, Check, CheckCheck, MessageCircle, RefreshCw, Send, X } from 'lucide-react';
import { Avatar, icon } from './chat-shared';
import { displayId } from '../lib/normalize';
import { useChat } from '../hooks/use-chat';
import type { ChatMessage } from '../lib/types';

function Bubble({ item }: { item: ChatMessage }) {
  const outgoing = item.direction === 'outgoing';
  const time = new Intl.DateTimeFormat('ru', { hour: '2-digit', minute: '2-digit' }).format(item.timestamp * 1000);
  const status = item.pending ? 'Отправляем' : ({ read: 'Прочитано', delivered: 'Доставлено', sent: 'Отправлено' } as Record<string, string>)[item.status ?? ''] ?? 'Отправлено';
  return <div className={`flex ${outgoing ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[80%] min-w-24 rounded-2xl px-3 pt-2.5 pb-1.5 shadow-sm ${outgoing ? 'rounded-br-sm bg-[#d9f2df]' : 'rounded-bl-sm bg-white'}`}><p className="break-words whitespace-pre-wrap text-[13px] leading-5 text-slate-800">{item.text}</p><div className="mt-1 flex items-center justify-end gap-1 text-[10px] text-slate-500"><time>{time}</time>{outgoing && <span title={status} aria-label={status} className={item.status === 'read' ? 'text-blue-500' : 'text-slate-500'}>{item.status === 'read' || item.status === 'delivered' ? <CheckCheck size={14} /> : <Check size={14} />}</span>}</div></div></div>;
}

export function Conversation({ app, mobileChat, close }: { app: ReturnType<typeof useChat>; mobileChat: boolean; close: () => void }) {
  const [draft, setDraft] = useState(''); const bottom = useRef<HTMLDivElement>(null);
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: 'smooth' }); }, [app.selected, app.messages.length]);
  async function submit(event: React.FormEvent) { event.preventDefault(); const text = draft.trim(); if (!text) return; setDraft(''); try { await app.send(text); } catch { setDraft(text); } }
  return <section className={`flex min-w-0 flex-1 flex-col bg-[#f8faf8] ${!mobileChat ? 'hidden md:flex' : ''}`}>{app.current ? <><header className="flex h-[78px] shrink-0 items-center gap-3 border-b border-slate-100 bg-white px-4 md:px-7"><button className={`${icon} md:hidden`} onClick={close} title="Назад"><ArrowLeft size={21} /></button><Avatar chat={app.current} /><div className="min-w-0 flex-1"><strong className="block truncate font-display text-sm font-bold text-slate-800">{app.current.name}</strong><span className="text-xs text-slate-400">{displayId(app.current.id)}</span></div><button className={icon} title="Обновить" onClick={() => void app.refresh()}><RefreshCw size={18} /></button></header><div className="flex min-h-0 flex-1 flex-col gap-2 overflow-y-auto bg-[#f5f8f5] px-4 py-6 md:px-14 2xl:px-40"><div className="mx-auto mb-4 rounded-full border border-slate-100 bg-white px-4 py-1.5 text-[11px] text-slate-500">История сообщений</div>{app.historyQuery.isLoading && !app.messages.length ? <div className="m-auto text-sm text-slate-500">Загружаем сообщения...</div> : app.messages.length ? app.messages.map(item => <Bubble item={item} key={item.id} />) : <div className="m-auto max-w-xs text-center"><div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-emerald-100 text-emerald-600"><MessageCircle size={32} /></div><h3 className="font-display text-lg font-extrabold text-slate-800">Начните разговор</h3><p className="mt-2 text-sm leading-6 text-slate-500">Напишите первое сообщение. Ответы появятся здесь автоматически.</p></div>}<div ref={bottom} /></div>{app.error && <div role="alert" className="mx-4 mb-2 flex justify-between rounded-lg bg-red-50 px-3 py-2 text-xs text-red-700 md:mx-7">{app.error}<button onClick={() => app.setError('')}><X size={16} /></button></div>}<form className="flex items-center gap-3 border-t border-slate-100 bg-white px-4 py-3 md:px-7" onSubmit={submit}><input className="h-11 min-w-0 flex-1 rounded-xl border border-slate-100 bg-slate-50 px-4 text-sm outline-none focus:border-emerald-500" placeholder="Напишите сообщение..." aria-label="Сообщение" value={draft} onChange={e => setDraft(e.target.value)} maxLength={20000} /><button className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-emerald-600 text-white disabled:opacity-50" title="Отправить" disabled={!draft.trim() || app.sending}><Send size={19} /></button></form></> : <div className="m-auto max-w-sm px-7 text-center"><div className="mx-auto mb-9 flex h-28 w-28 items-center justify-center rounded-4xl bg-emerald-100 text-emerald-600"><MessageCircle size={52} /></div><h1 className="font-display text-3xl font-extrabold text-slate-800">Оставайтесь на связи</h1><p className="mt-3 text-sm leading-6 text-slate-500">Выберите чат или создайте новый, чтобы отправить сообщение.</p></div>}</section>;
}

